# This is a basic workflow to help you get started with Actions

name: Docker Series Build

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # Runs a single command using the runners shell
    - name: docker build
      run: |
        docker build -t python-fhir .
    - name: postgres
      run: docker-compose -f "docker-compose.yml"
    - name: docker push
      run: |
        docker push v1tal303/emis-data-eng-assessment:tagname
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: v1tal303/emis-data-eng-assessment
        tags: latest, ${{ github.run_number }}
