# This is a basic workflow to help you get started with Actions

name: Docker Series Build

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # Runs a single command using the runners shell
    - name: docker build
      run: |
        docker build -t python-fhir .
    - name: postgres
      run: docker-compose -f "docker-compose.yml"
