# This is a basic workflow to help you get started with Actions

name: Docker Series Build

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # Runs a single command using the runners shell
    - name: docker build
      run: |
        docker build -t python-fhir .
    - name: postgres
      run: docker-compose -f "docker-compose.yml"
